### ISSUE TITLE
HA core-2021.6 не подключает компонент

### ISSUE THREAD

**Issue by aatumaykin** [AlexxIT/yandex_smart_home_fix#2]
_The custom integration 'yandex_smart_home_fix' does not have a valid version key (None) in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details_

Мешает перезагрузке HA, так как не проходит проверка конфига

**Comment by ARNik** [comment]
You don't need this fix anymore. Just delete it.

Этот фикс нужен только для конкретной старой версии HA. Сейчас его можно удалить.

**Comment by AlexxIT** [comment]
Да, фикс больше не нужен
